import { Account, WillConfig, DeadManConfig } from '@/types';

export const USE_MOCK = process.env.NEXT_PUBLIC_USE_MOCK === 'true';

export const MOCK_ACCOUNTS: Account[] = [
  {
    id: '1',
    userId: 'u1',
    serviceName: 'HDFC Bank',
    category: 'financial',
    riskScore: 94,
    riskReason: 'Direct access to funds. Prime phishing target.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: 'u1',
    serviceName: 'Zerodha',
    category: 'financial',
    riskScore: 91,
    riskReason: 'Stock trading account. Irreversible transactions possible.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    userId: 'u1',
    serviceName: 'Coinbase',
    category: 'crypto',
    riskScore: 98,
    riskReason: 'Crypto exchange. Irreversible. Extreme risk if unmanaged.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    userId: 'u1',
    serviceName: 'Google Drive',
    category: 'storage',
    riskScore: 85,
    riskReason: 'Contains personal documents, photos, private files.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    userId: 'u1',
    serviceName: 'Apple ID',
    category: 'storage',
    riskScore: 88,
    riskReason: 'Controls iCloud storage, purchases, and device recovery.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    userId: 'u1',
    serviceName: 'LinkedIn',
    category: 'work',
    riskScore: 65,
    riskReason: 'Professional identity and network. Moderate risk.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    userId: 'u1',
    serviceName: 'GitHub',
    category: 'work',
    riskScore: 70,
    riskReason: 'Contains private code repositories and SSH keys.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    userId: 'u1',
    serviceName: 'Instagram',
    category: 'social',
    riskScore: 58,
    riskReason: 'Personal photos and social connections. Identity risk.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    userId: 'u1',
    serviceName: 'Dropbox',
    category: 'storage',
    riskScore: 75,
    riskReason: 'Cloud file backup. Sensitive documents likely stored.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    userId: 'u1',
    serviceName: 'Netflix',
    category: 'entertainment',
    riskScore: 22,
    riskReason: 'Low financial exposure. Easy to cancel.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '11',
    userId: 'u1',
    serviceName: 'Spotify',
    category: 'entertainment',
    riskScore: 18,
    riskReason: 'Subscription-only. Negligible data risk.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    userId: 'u1',
    serviceName: 'Notion',
    category: 'work',
    riskScore: 55,
    riskReason: 'May contain private notes, project plans, credentials.',
    decision: 'undecided',
    discoveredVia: 'gmail',
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_WILL: WillConfig = {
  id: 'w1',
  trustedContactName: '',
  trustedContactEmail: '',
  customMessage: '',
};

export const MOCK_DEADMAN: DeadManConfig = {
  id: 'd1',
  thresholdDays: 30,
  isActive: false,
};
